### ISSUE TITLE
Zonen (farblich) unterscheiden zwischen "selektiert" und "nicht selektiert".

### ISSUE THREAD

**Issue by Kartinator** [geops/trafimage-maps#11]
In CASA unterscheiden wir bei Abos zwischen inkludierte Zonen und mögliche Zonen.

Inkludierte Zonen sind im gewählten Abo bereits enthalten.
Mögliche Zonen können optional dazu gewählt werden.
Wir müssen diese Zonen in der Karte (farblich) unterscheiden können. Diese Funktion konnte man in der "alten" Karte noch verwenden.

Beispiel von der alten Karte:
![image](https://user-images.githubusercontent.com/53262929/61793106-9a26d980-ae1e-11e9-8ca1-99e3100b9b5e.png)

**Comment by mhaertwig** [comment]
Umgesetzt in #17. 

Das Styling der Zonen ist konfigurierbar. Selektierte Zonen können anders eingefärbt werden als nicht selektierte. Beispiel: https://trafimage-maps.netlify.com/#section-casa

Wir verbessern aktuell die Layer-Doku. Weil diese die neuen Parameter noch nicht enthält, hier eine kurz-Doku in Textform:

Beim Aufruf des Layers kann mit dem Attribut `zoneStyle` der globale Style der Zonen definiert werden.
```
  const zoneLayer = new ZoneLayer({
    token: '...',
    zoneStyle: {
      stroke: { width: 0 },
    },
  });
```

Per Default wird folgender Style verwendet:
```
    {
      fill: {
        color: 'rgb(255, 200, 25)',
      },
      stroke: {
        width: 2,
        color: 'black',
      },
      text: {
        font: '12px Arial',
        color: 'black',
      },
    };
```

Mit der neuen `zoneStyleFunction` kann das Styling der Zonen dynamisch geändert werden:
```
  const zoneLayer = new ZoneLayer({
    token: '...',
    zoneStyleFunction: (zoneProps, isSelected) => {
      return {
        fill: {
          color: isSelected ? 'red' : 'rgb(255, 200, 25)',
        },
      };
    },
  });
``` 

Was sagt Ihr zur API? Wenn Ihr Änderungswünsche habt, dann teilt uns diese gern mit.
