### ISSUE TITLE
Language of Maps

### ISSUE THREAD

**Issue by ManueleRa** [geops/trafimage-maps#1135]
When routing on sbb.ch the starting and ending points are in English and not in the user's language (printscreen 1 shows Track and Platform instead of "Gleis" and "Kante").

On Mobile SBB the departure and arrival points are translated, but (at least in Italian) they do not correspond to the SBB wordings. For example, instead of "Corsia" on the map appears "Marciapiede" (see printscreen 2).

Furthermore, the language of the sidewalks (in this case "Kante A") also does not match the language used on sbb.ch (see printscreen 3)

Screenshot 1:
![Screenshot 1](https://github.com/geops/trafimage-maps/assets/155519646/534e3a1a-ca8e-401d-8019-696fadb957c7)

Screenshot 2:
![Screenshot 2](https://github.com/geops/trafimage-maps/assets/155519646/d35c77ea-cbb4-4815-9fcc-c0513a230e6a)

Screenshot 3:
![Screenshot 3](https://github.com/geops/trafimage-maps/assets/155519646/04740383-4316-4d9a-b867-232d8f134a02)

**Comment by roob1n** [comment]
Hello @ManueleRa 
This repository contains the web component used by the Trafimage map portal ([trafimage.sbb.ch](https://maps.trafimage.ch/)), however this component is not used in sbb.ch. 

Regarding your feedback:
- Translation of the destination and arrival points -> This is a bug and I will forward it to the corresponding team.
- Italian naming: I will have a look on why this term was chosen.
- Naming in sbb.ch vs naming on the map: The map is currently not internationalised. This is an open topic at Trafimage.

I will respond to your e-mail later on, so we can have a brief discussion.
