### ISSUE TITLE
Route Bern - Zürich HB kann nicht angezeigt werden wegen "Bahn-2000-Strecke"

### ISSUE THREAD

**Issue by Kartinator** [geops/trafimage-maps#12]
Die Strecke Bern - Zürich HB enthält als "Zwischenhalt" die Bahn-2000-Strecke. (UIC Code 132). Deswegen kann die Route nicht dargestellt werden.

Aufruf an's API:

https://geops.cloud.tyk.io/routing?token=myToken&via=!8507000%3B!132%3B!132%3B!8503000&mot=rail

**Comment by Kartinator** [comment]
@mhaertwig 

Weitere Strecken, die nicht klappen:

Zürich HB nach Lugano
Evtl. wegen Gotthardbasistunnel...?

Bern nach Sion
Evtl. wegen Lötschbergbasistunnel...?

Bei Bedarf kann ich dann noch alle UIC Codes raussuchen.

**Comment by lb1c** [comment]
Ping @mhaertwig

**Comment by lb1c** [comment]
Close because of age of the issue. Feel free to recreate another issue if the problem persist until today.
