### ISSUE TITLE
ZoneLayer: Zone & Partner auslesen beim Click-Callback	

### ISSUE THREAD

**Issue by Kartinator** [geops/trafimage-maps#13]
Aktuell lese ich Zone und Partner Code wie folgt aus:

```
zoneLayer.onClick(e => {
    var zone = e[0].getProperties()['zone']
    var partnerCode = e[0].getProperties()['partner_code']
});
```

Geht's irgendwie sauberer? Oder ist das der richtige Weg?

**Comment by mhaertwig** [comment]
Der Code passt so. Die `onClick`-Funktion wird mit einer Liste von OpenLayers-Features aufgerufen (s. https://openlayers.org/en/latest/apidoc/module-ol_Feature-Feature.html). Neben `getProperties()` haben diese auch eine einfache `get()` Funktion.
